### ISSUE TITLE
Uplift Demo Fix Hitlist

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2072]
**Is your feature request related to a problem? Please describe.**
A ticket to capture small issues with uplift implementation that we can address quickly to improve overall demonstrability of the Uplift theme

**Describe the solution you'd like**

- [x] Datagrid header color
- [x] Header title font size
---
(Update) associated issues:
- [x] #2251 
- [ ] #2211 
- [ ] #2212

**Comment by nickwynja** [comment]
```css
[class^='btn'] > * {
    vertical-align: top;
}
```
