### ISSUE TITLE
[Editor] Hyperlinks not clickable when readonly

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#4702]
**Describe the bug**
https://github.com/infor-design/enterprise/pull/4215 seem to have broken the behavior and functionality of Hyperlinks in a read-only editor. The following css (light-theme.css) makes them non-clickable, and the links are indistinguishable
from other text nodes (black color) if it is the first element in the editor. See demo below

```css
.editor-container.is-readonly .editor a {
  pointer-events: none;
}

.editor-container.is-readonly .editor > * {
  color: #1a1a1a !important;
}
```

**Version**
- ids-enterprise: 4.35.0 (but the bug was introduced when we upgraded to 4.33.0)

**Screenshots**

https://user-images.githubusercontent.com/4991954/102797027-62271b80-43af-11eb-98f8-51d4fe0ee6dd.mov

https://user-images.githubusercontent.com/4991954/102797040-64897580-43af-11eb-9d4e-a5cde60188e7.mov

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10, MacOS Big Sur
 - Browser Name: Chrome, Safari

**Additional context**
https://jira.infor.com/browse/LIME-6575
